- 02_code_organisation/readme.md
Made a few minor spelling corrections.
> minor spelling corrections

- 02_code_organisation/readme.md
- README.md
Corrected a few spelling mistakes - there are still spelling mistakes left that need correction.
> Corrected spelling of Repository 

- README.md
Thought the README-page could use some memes to follow along the presentations - so I added one!
> added a meme

- 02_code_organisation/readme.md
Change "reposatory" to "repository"
> Fix spelling of "repository"

- 02_code_organisation/readme.md
reposatory -> repository
enviroment -> environment
> Fix spelling errors

- 02_code_organisation/readme.md
Corrected from cooding to coding :-)
> spelling error correction

- 02_code_organisation/readme.md
Changed the spelling of 'reposatory' to 'repository'
> Testing creating a pull request by fixing reposatory spelling

- 02_code_organisation/readme.md
modified:   02_code_organisation/readme.md
Reposatory replaced with repository (i initially couldn't find the spelling error wauw)
> Changes to be committed:

- 09_crossvalidation_at_scale/.vscode/settings.json
- 09_crossvalidation_at_scale/readme.md
Fixed a spelling mistake in week 9 readme
> Feature spelling mistakes

- 10_deployment/readme.md
> updated day number

- 01_introduction/1_Tensors_in_PyTorch.ipynb
The introduction have been changed marginally.
> Changed introductory text

- 02_code_organisation/readme.md
I have changed a few things including the spelling of "repository", and one command.
> changing grammar and one git command

- 01_introduction/3_Training_Neural_Networks.ipynb
It would be more proper to evaluate the model on a test set than the training set.
> We train and test/evaluate on the same data so not so brilliant

- 02_code_organisation/readme.md
Changed small spelling mistake for a folder name: scr -> src
> Changed small spelling mistake for a folder name

- 05_project_overview/readme.md
I corrected the requirement file name in the checkbox list
> Rename requirement.py to requirements.txt in readme for week 05

- s1_getting_started/exercise_files/1_Tensors_in_PyTorch.ipynb
- s1_getting_started/exercise_files/2_Neural_Networks_in_PyTorch.ipynb
New lines were missing in the last section of the first Pytorch notebook (Numpy <> PyTorch part). 
I added them, so that the code works :)
> Add new lines in first Pytorch notebook

- s1_getting_started/M1_terminal.md
Fixed some spelling mistakes in the MD file of S1 M1 Terminal
> fixing spelling mistakes in M1_terminal

- s2_organisation_and_version_control/S2.md
Solved some misspellings in S2.md
> misspellings in S2.md

- s2_organisation_and_version_control/M5_git.md
Spelling and punctuation in M5.
> Spelling mistakes m5

- s2_organisation_and_version_control/M5_git.md
s202825 addition to exercise 4e)
> Changed spelling from reposatory to repository in M5

- s1_getting_started/M3_editor.md
Companies and names should be capitalized.
> 	modified:   s1_getting_started/M3_editor.md

- projects/projects.md
- s2_organisation_and_version_control/S2.md
- s7_scalable_applications/S7.md
Links to s10_extra files one number too low.
> Fixed broken links

- s1_getting_started/exercise_files/3_Training_Neural_Networks.ipynb
> grammar correction

- s2_organisation_and_version_control/M7_good_coding_practice.md
Hi, I have added a new resource for Data Types, where I gave a reference for Data Types in C++. I thought it to be useful for this article and added it here. Hope this small contribution will help other learners.
> Added a new resource

- s6_the_cloud/S6.md
> What's instead of whats

- README.md
Added important learning objective
> add extra learning objective to readme

- README.md
I fixed a single spelling mistake:)
> Spelling mistake fixed

- README.md
My super valuable and incredibly useful contribution to this repo is that I changed "Machine Learning **Opeartions**" to "Machine Learning **Operations**" in the cite at the end. You are most welcome Nicki 😎
> Fixed spelling mistake in ref at the end of READ.ME :)

- s1_development_environment/deep_learning_software.md
Correct spelling mistakes in a deep learning exercises.
> Correct spelling mistake

- s2_organisation_and_version_control/git.md
I changed: "make changes to THE repository" (day 2: git)
> make changes to THE repository(day 2: git)

- s2_organisation_and_version_control/git.md
> Fixed typo

- s1_development_environment/deep_learning_software.md
Looks like a mistake trying to type fulfill
> Fulfill spelling mistake

- s1_development_environment/S1.md
> fix a typo

- s2_organisation_and_version_control/git.md
Added a joke created by ChatGPT
> added text

- s1_development_environment/deep_learning_software.md
corrected a couple of spelling mistakes in the deep learning software module
> Spelling mistakes in deep_learning_software.md

- s1_development_environment/deep_learning_software.md
Spelling mistake in the s1_development_environment (software) explanation.
> Spelling mistake found

- s1_development_environment/exercise_files/final_exercise/data.py
- s1_development_environment/exercise_files/final_exercise/main.py
Added "import numpy as np" to s1_development_environment/exercise_files/final_exercise/data.py
Deleted empty lines in s1_development_environment/exercise_files/final_exercise/main.py
> little changes on s1_development_environment/exercise_files/final_exercise

- s2_organisation_and_version_control/git.md
> "Github" instead of "github"

- s1_development_environment/deep_learning_software.md
Fixed spelling error in deep_learning_software.md
> Changed dept -> debt

- s2_organisation_and_version_control/good_coding_practice.md
Added the new type expressions from python 3.10
> Added new typing syntax

- s6_the_cloud/cloud_setup.md
I've changed three spelling mistakes in this chapter :)
> Spelling mistakes

- s1_development_environment/exercise_files/1_Tensors_in_PyTorch.ipynb
- s2_organisation_and_version_control/git.md
Adding full stops in comments of this notebook.
> Adding full stops.

- s6_the_cloud/using_the_cloud.md
Seems like it is the same exercise as in step 9.. If it is not the case, it is not clear what is the difference and I would suggest to specify it differently :).
> duplicate exercise (-->9. == 11.)

- s7_deployment/apis.md
> My branchy

- README.md
changed 'actual' to 'actually', which is grammatically correct. it says it changed other lines too, but those don't even exist on my up-to-date main branch, so i'm not sure what that is about
> actual to actually

- s7_deployment/S7.md
- s7_deployment/apis.md
Fixed grammatical and spelling errors of S7 (the main and API).
> Fixed spelling

- s1_development_environment/editor.md
Fixed 2 typos in lecture 1 - editor.md
> Fixed typos VC->VS

- projects.md
- s4_debugging_and_logging/exercise_files/vae_mnist_working.py
- s4_debugging_and_logging/logging.md
- added "mps" as device to support M1 and M2 apple gpu
- fixed a couple of typos in the project description
- fixed typo in logging
> S4 m1 silicon support

- mkdocs.yml
> Typo in the menu bar

- s1_development_environment/deep_learning_software.md
- s2_organisation_and_version_control/code_structure.md
Fixed a reference to requirements as `requirements.py` to `requirements.txt`.
> Fixed typo when referring to requirements

- s1_development_environment/exercise_files/5_Inference_and_Validation.ipynb
I had some confusion with this part so I provided some extra clarity to what actually happens.
> Add clarity to avoid confusion regarding shapes

- s2_organisation_and_version_control/git.md
> Correct capitalization of GitHub

- s1_development_environment/README.md
- s1_development_environment/deep_learning_software.md
Change N -> M in the code for Knowlegde Check
> Changed error in the code (Knowlegde check)

- s1_development_environment/editor.md
> fixed minor typo

- faq.md
> edited answer of LLM tools question in faq.md

- s2_organisation_and_version_control/code_structure.md
Add the location of the folder containing the data used in exercise 2.
> Add folder of data needed for exercise 2

- s3_reproducibility/docker.md
I sit on the porch
Behind me, it suffers
I hear it coming, torch
For the ninth time today
I hear its labored grunts, the words of a self-sacrificial hero
The words I hear it say:
'collecting torch==2.1.0'
> add guide to cache pip installation during docker build

- s6_the_cloud/using_the_cloud.md
Fixed tag command when pushing to google cloud
> Fixed commands in  using_the_cloud.md

- s1_development_environment/README.md
- s2_organisation_and_version_control/code_structure.md
Added punctuation and other insignificant literature changes.
> Minor changes to literature

- s1_development_environment/exercise_files/final_exercise/data_solution.py
- s1_development_environment/exercise_files/final_exercise/main.py
Fix two small errors inside the "s1_development_environment/exercise_files/final_exercise/data_solution.py".
> [Debug]Fix Errors inside the codes

- mkdocs.yml
Corrected name of day 3 from  "S3 - Reproduceability ♻️:" to   "S3 - Reproducibility ♻️:"
> Spelling error in title of day 3.

- s2_organisation_and_version_control/cli.md
- s2_organisation_and_version_control/code_structure.md
Hi, I noticed some minor typos in some of the material for the section S2, so I've updated these in this pr.
> Minor typos

- s2_organisation_and_version_control/README.md
It is to enhance the vocabulary of the text
> some minor grammatical fixes

- s6_the_cloud/README.md
Changing typo for consistency through the text.
> Fix typo in README.md

- s1_development_environment/deep_learning_software.md
When both the starting point for the script, `data.py`, and the related solution are provided, the reported filename is incorrectly shown as `model.py` instead of `data.py`.
> Fix filename from model.py to data.py

- s7_deployment/ml_deployment.md
Fixing two minor spelling mistakes.
> Fixing spelling mistakes in S7

- README.md
I added "underfitting" aswell.
> Changed some text in README file

- s1_development_environment/README.md
I removed two periods so that all the bullet points were consistent and changed "being able" to "be able" so that all the bullets had the same grammatical structure.
> Standardized the learning objectives section

- s3_reproducibility/exercise_files/vae_mnist.py
Assumes available, but should be dynamically check
> Update cuda check dynamically
